### ISSUE TITLE
Convert to role for inclusion on galaxy

### ISSUE THREAD

**Issue by conorsch** [timurb/ansible-digitalocean-vpn#5]
Not sure if you're still maintaining this. I'd like to fork the repo and toss it up on galaxy.ansible.com, so I can include it more easily in personal projects. In the process I'll need to restructure the project as a role, with default vars and other boilerplate. Let me know if you'd like to submit it to galaxy, otherwise I'll go ahead with the fork.

**Comment by timurb** [comment]
I'm afraid I'm not planning to maintain the project at the moment as I have other means of VPN.
So you are free to go forward with forking the project and uploading it to Galaxy.

**Comment by conorsch** [comment]
Thanks for the prompt response, I'll start cutting it up into a role now!

**Comment by timurb** [comment]
You are welcome!
You'd also probably want to check some pull requests I didn't have a chance to merge.
